version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @nestjs/cli

  pre_build:
    commands:
      - echo "Running database migration..."
      - npm run migration:run

  build:
    commands:
      - echo "Building NestJS application..."
      - npm run build

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'
# env:
#   variables:
#     DATABASE_HOST: 'database-1.c5mcos2y8cv7.ap-northeast-2.rds.amazonaws.com'
